import type {Metadata} from "next";
import {Lato} from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const lato = Lato({subsets: ["latin"], weight: ["300", "400", "700"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={clsx(
                "bg-slate-200 bg-gradient-to-t from-slate-300 to-slate-200 to-100%",
                lato.className
            )}
        >
        <div className="flex flex-col min-h-screen">
            <header>header</header>
            <main className="flex-grow">{children}</main>
            <footer>footer</footer>
        </div>
        </body>
        </html>
    );
}
